// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication;

namespace WebApplication.Migrations
{
    [DbContext(typeof(QuotesDBContext))]
    partial class QuotesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("WebApplication.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Identification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3d05112-fae7-4e44-8e49-3824f80fdeb0"),
                            AccountCode = 2551,
                            Identification = true,
                            LastName = "Boluevna",
                            Name = "Olucha"
                        },
                        new
                        {
                            Id = new Guid("1b2369f3-626f-43bb-b1e8-2aee11ac47d5"),
                            AccountCode = 2883,
                            Identification = true,
                            LastName = "holova",
                            Name = "Anora"
                        });
                });

            modelBuilder.Entity("WebApplication.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("WebApplication.Client", b =>
                {
                    b.HasOne("WebApplication.Client", null)
                        .WithMany("Clients")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("WebApplication.Wallet", b =>
                {
                    b.HasOne("WebApplication.Client", "Client")
                        .WithMany("Wallets")
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApplication.Client", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
